### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by simon-p-r** [dschenkelman/z-schema-errors#2]
Hi

I just tried using your module however this error happened.

``` js

D:\Modules\yajsv\node_modules\z-schema-errors\lib\index.js:20
        return path.substr(2).replace(/\//g, '.').replace(/\.([0-9]+)/g, '[$1]
                    ^
TypeError: undefined is not a function
    at Object.DEFAULT_EXTRACTORS.path (D:\Modules\yajsv\node_modules\z-schema-errors\lib\index.js:20:21)
    at D:\Modules\yajsv\node_modules\z-schema-errors\lib\index.js:76:22
    at Array.reduce (native)
    at formatMessage (D:\Modules\yajsv\node_modules\z-schema-errors\lib\index.js:59:27)
    at D:\Modules\yajsv\node_modules\z-schema-errors\lib\index.js:111:14
    at Array.map (native)
    at Object.extractMessage (D:\Modules\yajsv\node_modules\z-schema-errors\lib\index.js:105:35)
    at internals.Manager.compile (D:\Modules\yajsv\lib\index.js:31:33)
    at Object.<anonymous> (D:\Modules\yajsv\test.js:34:21)
    at Module._compile (module.js:460:26)
```

Thanks
Simon

**Comment by dschenkelman** [comment]
Hey Simon,

Thanks for reporting the issue. Can you add a `console.log('path', path)` just before that line? It seems a `path` is coming but it is not a string (which is weird).

Also, what version of z-schema are you using?

Thanks,

**Comment by simon-p-r** [comment]
Version of zSchema is 3.12.2 and the value of path on line 20 is an empty array.

**Comment by dschenkelman** [comment]
Could you please provide a small code repro sample so I can test on this side? Even better yet would a unit test that repros the issue :)

**Comment by simon-p-r** [comment]
Code is difficult to replicate in small form, I am collecting an array of schemas and then passing to zSchema to validate as an array.  The errors I am getting back are unclear hence why I used your module to try to decipher them.

**Comment by dschenkelman** [comment]
I understand Simon. The thing is, without a small repro sample I can only make the fix so that no error is thrown but no clear error messages will be provided, so that is not a good idea.

If you can get me a small repro sample I can try to figure out why the error is occurring and handle that scenario.

**Comment by simon-p-r** [comment]
I will close for now, I was passing invalid key within zSchema strict mode however this module should be able to format these errors as well.  The error it was failing on was this if you want to test for this in your logic

``` js
{ code: 'KEYWORD_UNDEFINED_STRICT',
  params: [ 'type' ],
  message: 'Keyword \'type\' must be defined in strict mode',
  path: [] }
```

Thanks

**Comment by dschenkelman** [comment]
@simon-p-r thanks for the feedback sorry for the delay. just updated the code with the fix: https://github.com/dschenkelman/z-schema-errors/pull/3 and published version 0.2.1 with it

**Comment by simon-p-r** [comment]
No problem, looks good!  :+1:

**Comment by simon-p-r** [comment]
It works well
